---
- name: register vm using credentials
  community.general.redhat_subscription:
    state: present
    username: "{{ rhUsername }}"
    password: "{{ rhPassword }}"
    pool_ids: "{{ rhPool }}"
    force_register: true

- name: install epel RPM key
  rpm_key:
    state: present
    key: "{{ epelRepoKey }}"

- name: install epel repository
  ansible.builtin.dnf:
    name: "{{ epelRepo }}"
    state: present

- name: enable Red Hat repositories
  ansible.builtin.shell: | 
    subscription-manager repos --enable={{ item }}
  loop: "{{ rhRepos }}"

- name: install key and repository for vscode
  ansible.builtin.shell: |
    rpm --import https://packages.microsoft.com/keys/microsoft.asc
    sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > {{ vscodeRepo }}'

- name: add docker repository
  ansible.builtin.shell: |
    dnf config-manager --add-repo "{{ dockerRepo }}"
  
- name: add github repository
  ansible.builtin.shell: |
    dnf config-manager --add-repo "{{ githubRepo }}"