---
- name: download GoLand tar.gz
  ansible.builtin.get_url:
    url: "{{ golandDownloadURL }}"
    dest: "/opt/{{ golandTarName }}"

- name: untar GoLand
  ansible.builtin.unarchive:
    src: "/opt/{{ golandTarName }}"
    dest: "/opt/"
    remote_src: yes 

- name: find GoLand start script
  ansible.builtin.find:
    path: "/opt/"
    patterns: 'goland.sh'
    recurse: yes
  register: golandStart

- name: delete alias for GoLand if exists
  ansible.builtin.file:
    path: "/etc/profile.d/{{ golandAlias }}"
    state: absent

- name: create alias for GoLand
  ansible.builtin.lineinfile:
    path: "/etc/profile.d/{{ golandAlias }}"
    line: alias goland="{{ item.path }}"
    create: yes
  loop: "{{ golandStart.files }}"

- name: delete GoLand tar.gz
  ansible.builtin.file:
    path: "/opt/{{ golandTarName }}"
    state: absent